### ISSUE TITLE
Fail with maven-surefire-plugin version >= 2.21.0 ClassNotFoundException: org.apache.maven.plugin.surefire.log.api.ConsoleLogger

### ISSUE THREAD

**Issue by gabrilogos1985** [gmu-swe/deflaker#2]
I added the extension Deflaker on my pom.xml project file. 
when I run `mvn clean test` fails:
**sufire plugin test ClassNotFoundException: org.apache.maven.plugin.surefire.log.api.ConsoleLogger**
I change maven-surefire-plugin version to 2.19.1 run `mvn clean test` and it compiles and finish test.
this is the except of my pom.xml

```
<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-surefire-plugin</artifactId>
				<version>2.21.0</version>
			</plugin>
		</plugins>
		<extensions>
			<extension>
				<groupId>org.deflaker</groupId>
				<artifactId>deflaker-maven-extension</artifactId>
				<version>1.4</version>
			</extension>
		</extensions>
	</build>
</project>

```

**Comment by jon-bell** [comment]
Thanks - I updated the readme. The last few versions of maven-surefire 2.XX introduced a lot of breaking changes for many projects, so I hesitate to change our compatibility to 2.21 (and lose backwards compatibility for many projects that won't upgrade their surefire dependency).
