### ISSUE TITLE
Tests won't run in intellij IDEA with DeFlaker

### ISSUE THREAD

**Issue by lsrcz** [gmu-swe/deflaker#4]
After Adding DeFlaker to the pom.xml, I can't run JUnit tests in intellij IDEA.
The error message is:
```text
Error: Could not find or load main class '-XX:OnOutOfMemoryError=kill
```
Changing all the `"'-XX:OnOutOfMemoryError=kill -9 %p' "` in [DeflakerLifecycleParticipant.java](https://github.com/gmu-swe/deflaker/blob/master/maven-extension/src/main/java/org/deflaker/maven/DeflakerLifecycleParticipant.java) to `"-XX:OnOutOfMemoryError='kill -9 %p' "` may help but I'm not sure.

**Comment by jon-bell** [comment]
Maven is integral for DeFlaker - you can only invoke it from Maven. To clarify: are you using IntelliJ's built-in test runner, or are you invoking maven from IntelliJ?

**Comment by lsrcz** [comment]
Sorry I am using IntelliJ's built-in test runner. I know IntelliJ is not smart enough when using with Maven, but it would be cool if I can use IntelliJ's convenient test runner with the tool seamlessly.

I found that installing DeFlaker site-wide really helps, so I am closing the issue.
Thanks!

**Comment by jon-bell** [comment]
OK - FYI, if this is something that you are interested in, I'm sure that there is some way to write an IntelliJ plugin for DeFlaker.
